name: autism-screening
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - matplotlib
  - seaborn
  - scipy
  - pip
  - pip:
    - PyYAML