# Model parameters
random_state: 42
test_size: 0.3
cv_folds: 5

# Model hyperparameters
lgbm_params:
  n_estimators: 150
  max_depth: 6
  learning_rate: 0.1
  class_weight: "balanced"

random_forest_params:
  n_estimators: 100
  max_depth: 6
  class_weight: "balanced"

logistic_regression_params:
  max_iter: 1000
  class_weight: "balanced"
  penalty: "l2"
  C: 1.0

# Cultural clustering
min_cluster_size: 20
cultural_regions:
  Anglo: ["united states", "united kingdom", "canada", "australia", "new zealand"]
  European: ["austria", "france", "germany", "netherlands", "italy", "spain"]
  Latin_American: ["brazil", "argentina", "mexico", "chile", "colombia"]
  South_Asian: ["india", "sri lanka", "pakistan", "bangladesh"]
  Middle_Eastern: ["jordan", "uae", "saudi arabia", "iran", "iraq"]
  East_Asian: ["china", "japan", "south korea", "taiwan", "singapore"]
  African: ["south africa", "nigeria", "kenya", "ghana"]

# Feature sets
feature_set_A:
  - "A1_Score"
  - "A2_Score"
  - "A3_Score"
  - "A4_Score"
  - "A5_Score"
  - "A6_Score"
  - "A7_Score"
  - "A8_Score"
  - "A9_Score"
  - "A10_Score"
  - "age"
  - "gender"
  - "jaundice"
  - "austim"

feature_set_B:
  extends: "feature_set_A"
  additional:
    - "cultural_cluster"

feature_set_C:
  extends: "feature_set_B"
  additional:
    - "cultural_region"
